spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/CoffeeMaker?createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true&serverTimezone=EST
    username: root
    password: 
    hikari:
      idleTimeout: 500
      connectionTimeout: 15000 
  jpa:
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.MySQL5Dialect
    show-sql: true

server:
  ssl:
    key-store: src/main/resources/springboot.jks
    key-store-password: testpassword
    key-store-type: jks
    key-alias: springboot
    key-password: testpassword
  port: 8080
